Repository peeratmac/rancid-tomatillos, pull requests merged in 2019-12, with the labels that each got.

#10 Boilerplate setup for all components planned and setup for redux by separating files into 4 appropriate directories
  package-lock.json
  package.json
  src/actions/index.js
  src/components/App.css
  src/components/App.js
  src/components/App.test.js
  src/components/MovieCard.js
  src/components/MovieShowPage.js
  src/containers/LoginForm.js
  src/containers/MovieContainer.js
  src/containers/NavigationBar.js
  src/reducers/index.js
  src/reducers/moviesReducer.js
Labels: initial-setup-toward-mvp

#12 Add buttons and basic layout to NavigationBar and correct path to App
  src/components/App.js
  src/containers/NavigationBar.css
  src/containers/NavigationBar.js
  src/index.js
Labels: initial-setup-toward-mvp

#11 Added apiCalls file to get all the movies returned. Redux store for all movies data.
  src/apiCalls.js
  src/components/App.js
  src/index.js
Labels: initial-setup-toward-mvp

#13 Routing Starter - dynamic routing for different movies display on the main route
  package-lock.json
  package.json
  src/components/App.js
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/containers/MovieContainer.js
  src/index.js
Labels: mvp-requirements

#14 Form
  package-lock.json
  package.json
  src/components/App.js
  src/components/MovieCard.js
  src/components/MovieCard.test.js
  src/components/MovieShowPage.css
  src/components/MovieShowPage.test.js
  src/containers/LoginForm.css
  src/containers/LoginForm.js
  src/containers/MovieContainer.css
  src/containers/MovieContainer.js
  src/containers/MovieContainer.test.js
  src/containers/NavigationBar.js
  src/setupTests.js
Labels: initial-setup-toward-mvp, mvp-requirements, unit-test-fundamentals

#18 Login
  src/actions/index.js
  src/apiCalls.js
  src/components/App.js
  src/containers/LoginForm.js
  src/containers/NavigationBar.js
  src/reducers/index.js
  src/reducers/userReducer.js
Labels: initial-setup-toward-mvp, mvp-requirements

#19 Action creator update, redux store update upon logging in for user, and logout routing
  src/actions/index.js
  src/components/App.js
  src/containers/LoginForm.js
  src/containers/NavigationBar.js
Labels: bug, mvp-requirements

#27 Movie show page - displaying specific movie information
  src/components/App.js
  src/components/MovieShowPage.css
  src/components/MovieShowPage.js
Labels: mvp-requirements

#33 Miscellaneous
  src/actions/actions.test.js
  src/components/App.js
  src/components/App.test.js
  src/components/MovieShowPage.js
  src/containers/LoginForm.js
  src/containers/MovieContainer.js
  src/containers/MovieContainer.test.js
  src/containers/NavigationBar.js
  src/reducers/errorReducer.test.js
  src/reducers/index.js
  src/reducers/loadingReducer.test.js
  src/reducers/loadingStatusReducer.js
  src/reducers/loadingStatusReducer.test.js
  src/reducers/userReducer.test.js
Labels: bug, unit-test-fundamentals

#34 Snapshot testing + PropTypes
  package.json
  src/components/App.js
  src/components/App.test.js
  src/components/MovieCard.js
  src/components/MovieCard.test.js
  src/components/MovieShowPage.js
  src/components/MovieShowPage.test.js
  src/components/__snapshots__/App.test.js.snap
  src/components/__snapshots__/MovieCard.test.js.snap
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/MovieContainer.js
  src/containers/MovieContainer.test.js
  src/containers/__snapshots__/MovieContainer.test.js.snap
Labels: unit-test-fundamentals

#35 Logout (and displaying buttons)
  src/actions/index.js
  src/apiCalls.js
  src/containers/LoginForm.js
  src/containers/NavigationBar.js
  src/reducers/index.js
  src/reducers/isLoggedInReducer.js
Labels: mvp-requirements

#36 Ratingstyle
  src/components/App.css
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/components/MovieShowPage.css
  src/components/MovieShowPage.js
  src/containers/LoginForm.css
  src/containers/MovieContainer.css
  src/containers/MovieContainer.js
  src/containers/NavigationBar.css
  src/containers/NavigationBar.js
Labels: styling

#37 Small changes with an addition of NavigationBar testing
  src/components/__snapshots__/MovieCard.test.js.snap
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/LoginForm.js
  src/containers/LoginForm.test.js
  src/containers/NavigationBar.js
  src/containers/NavigationBar.test.js
  src/containers/__snapshots__/LoginForm.test.js.snap
  src/containers/__snapshots__/MovieContainer.test.js.snap
  src/containers/__snapshots__/NavigationBar.test.js.snap
Labels: unit-test-fundamentals

#38 Fetch ratings
  src/actions/index.js
  src/apiCalls.js
  src/components/MovieShowPage.js
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/LoginForm.js
  src/reducers/index.js
  src/reducers/userReducer.js
Labels: mvp-requirements

#39 Setup rating update
  src/actions/actions.test.js
  src/components/MovieShowPage.js
  src/reducers/index.js
  src/reducers/userReducer.js
  src/reducers/userReducer.test.js
Labels: mvp-requirements, unit-test-fundamentals

#42 Update loader
  src/components/App.js
  src/containers/LoginForm.js
  src/containers/MovieContainer.js
  src/reducers/loadingStatusReducer.js
Labels: mvp-requirements, styling, unit-test-fundamentals

#44 Async testing
  src/apiCalls.test.js
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/__snapshots__/LoginForm.test.js.snap
  src/containers/__snapshots__/MovieContainer.test.js.snap
Labels: async-testing

#45 POST request to add user rating + show user rating (if user has rated)
  src/apiCalls.js
  src/components/MovieShowPage.js
Labels: bug, enhancement, mvp-requirements
