Repository peeratmac/rancid-tomatillos, pull requests merged in 2020-01, with the labels that each got.

#46 Holiday work
  src/actions/index.js
  src/apiCalls.js
  src/components/App.js
  src/components/App.test.js
  src/components/MovieCard.css
  src/components/MovieCard.js
  src/components/MovieShowPage.css
  src/components/MovieShowPage.js
  src/components/MovieShowPage.test.js
  src/components/__snapshots__/MovieCard.test.js.snap
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/LoginForm.css
  src/containers/LoginForm.js
  src/containers/LoginForm.test.js
  src/containers/MovieContainer.css
  src/containers/MovieContainer.test.js
  src/containers/NavigationBar.css
  src/containers/NavigationBar.js
  src/containers/NavigationBar.test.js
  src/containers/__snapshots__/LoginForm.test.js.snap
  src/images/curtains.jpeg
  src/images/tomato2.png
  src/reducers/isLoggedInReducer.test.js
Labels: redux-testing

#47 Testing unit hf
  src/components/MovieShowPage.js
  src/components/MovieShowPage.test.js
  src/components/__snapshots__/MovieShowPage.test.js.snap
  src/containers/LoginForm.test.js
  src/containers/MovieContainer.test.js
  src/containers/NavigationBar.test.js
  src/containers/__snapshots__/LoginForm.test.js.snap
  src/containers/__snapshots__/MovieContainer.test.js.snap
  src/containers/__snapshots__/NavigationBar.test.js.snap
Labels: unit-test-fundamentals

#61 Fetch calls testing for updateRatings and deleteRating
  src/apiCalls.test.js
Labels: async-testing

#66 Update rating error handling
  src/components/MovieShowPage.js
Labels: mvp-requirements
